// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ChatSource } from '../chat/chat-source';


export class ChatMessage implements flatbuffers.IUnpackableObject<ChatMessageT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatMessage(bb:flatbuffers.ByteBuffer, obj?:ChatMessage):ChatMessage {
  return (obj || new ChatMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatMessage(bb:flatbuffers.ByteBuffer, obj?:ChatMessage):ChatMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

source():ChatSource {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ChatSource.System;
}

mutate_source(value:ChatSource):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt8(this.bb_pos + offset, value);
  return true;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startChatMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSource(builder:flatbuffers.Builder, source:ChatSource) {
  builder.addFieldInt8(0, source, ChatSource.System);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static endChatMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChatMessage(builder:flatbuffers.Builder, source:ChatSource, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  ChatMessage.startChatMessage(builder);
  ChatMessage.addSource(builder, source);
  ChatMessage.addMessage(builder, messageOffset);
  return ChatMessage.endChatMessage(builder);
}

unpack(): ChatMessageT {
  return new ChatMessageT(
    this.source(),
    this.message()
  );
}


unpackTo(_o: ChatMessageT): void {
  _o.source = this.source();
  _o.message = this.message();
}
}

export class ChatMessageT implements flatbuffers.IGeneratedObject {
constructor(
  public source: ChatSource = ChatSource.System,
  public message: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const message = (this.message !== null ? builder.createString(this.message!) : 0);

  return ChatMessage.createChatMessage(builder,
    this.source,
    message
  );
}
}
