version: "3.8"

services:
    jenkins:
        stdin_open: true
        tty: true
        env_file: .env
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                JENKINS_HOME: /var/lib/jenkins
                COPY_REFERENCE_FILE_LOG: /var/lib/jenkins/copy_reference.log
                CONTAINER_HOME: /home/jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        user: "root:root"
