// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Player } from '../player/player';
import { User } from '../user/user';


export class InputPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InputPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInputPayload(bb:flatbuffers.ByteBuffer, obj?:InputPayload):InputPayload {
  return (obj || new InputPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInputPayload(bb:flatbuffers.ByteBuffer, obj?:InputPayload):InputPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InputPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

user(obj?:User):User|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new User()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

player(obj?:Player):Player|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Player()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startInputPayload(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addUser(builder:flatbuffers.Builder, userOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, userOffset, 0);
}

static addPlayer(builder:flatbuffers.Builder, playerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, playerOffset, 0);
}

static endInputPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
