// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { User, UserT } from '../user/user';


export class QueryStatePayload implements flatbuffers.IUnpackableObject<QueryStatePayloadT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):QueryStatePayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQueryStatePayload(bb:flatbuffers.ByteBuffer, obj?:QueryStatePayload):QueryStatePayload {
  return (obj || new QueryStatePayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQueryStatePayload(bb:flatbuffers.ByteBuffer, obj?:QueryStatePayload):QueryStatePayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QueryStatePayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

user(obj?:User):User|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new User()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startQueryStatePayload(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUser(builder:flatbuffers.Builder, userOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, userOffset, 0);
}

static endQueryStatePayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createQueryStatePayload(builder:flatbuffers.Builder, userOffset:flatbuffers.Offset):flatbuffers.Offset {
  QueryStatePayload.startQueryStatePayload(builder);
  QueryStatePayload.addUser(builder, userOffset);
  return QueryStatePayload.endQueryStatePayload(builder);
}

unpack(): QueryStatePayloadT {
  return new QueryStatePayloadT(
    (this.user() !== null ? this.user()!.unpack() : null)
  );
}


unpackTo(_o: QueryStatePayloadT): void {
  _o.user = (this.user() !== null ? this.user()!.unpack() : null);
}
}

export class QueryStatePayloadT implements flatbuffers.IGeneratedObject {
constructor(
  public user: UserT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const user = (this.user !== null ? this.user!.pack(builder) : 0);

  return QueryStatePayload.createQueryStatePayload(builder,
    user
  );
}
}
