name: Build Server

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main", "stage" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Cache
      uses: actions/cache@v2.1.8
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: /server/target
        # An explicit key for restoring and saving the cache
        key: "server-cache"
