name: Build Server

on:
  push:
    branches: [ "main", "stage", "staging" ]
  pull_request:
    branches: [ "main", "stage", "staging" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3
    - name: Cache build
      id: cache-build
      uses: actions/cache@v3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              server/target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('server/Cargo.lock') }}

    - name: Build
      if: steps.cache-build.outputs.cache-hit != true
      run: cargo build --verbose
