name: Fun-Software CI/CD

on:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test server
      run: |
        cd server
        cargo test
