name: Fun-Software CI/CD

on:
  push:
    branches:
      - main
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Server tests
      run: |
        cd server
        cargo test
    - name: Client tests
      run: |
        cd client
        npm run test
