jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  globalNodeProperties:
  - envVars:
      env:
        - key: "DONOVAN_TEST"
          value: "${DONOVAN_TEST}"
  mode: NORMAL
  numExecutors: 5
  projectNamingStrategy: "standard"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
